@startuml pms
start
:メイン画面表示;
if ("宿泊ボタンを押した場合") then (Yes)
    :宿泊プラン選択画面表示;
    :プラン選択;
    :部屋種類・宿泊人数・宿泊オプション選択画面表示;
    :日程カレンダー表示;
    :日程選択;
    :名前とメールアドレス入力画面表示;
    :入力完了後メールアドレス宛に見積もり情報送信;
else if ("宴会ボタンを押した場合") then (Yes)
    :宴会プラン選択画面表示;
    :プラン選択;
    :宿泊人数・宴会オプション選択画面表示;
    :日程カレンダー表示;
    :日程選択;
    :名前とメールアドレス入力画面表示;
    :入力完了後メールアドレス宛に見積もり情報送信;
endif
stop
@enduml